const products = [
    {
        _id: '1',
        name: 'Mi Air Purifier',
        image: '/img/airPurifier.png',
        descripton: 'The Mi Air Purifier comes with a high-precision laser PM sensor that detects microscopic particulates and reports changes in room air quality in real time.',
        brand: 'Xiaomi',
        category: 'Electronics',
        price: 19999,
        countInStock: 0,
        ratings: 4.3,
        numReviews: 5,
    },
    {
        _id: '2',
        name: 'Mi Fitness Band 5',
        image: '/img/band5.png',
        descripton: 'Mi Fitness Band 5 has a 1.1-inch, 126x294 resolution capacitive AMOLED display and 24/7 heart rate monitoring claiming a 50% more accurate PPG sensor than its predecessor.',
        brand: 'Xiaomi',
        category: 'Electronics',
        price: 2999,
        countInStock: 7,
        ratings: 4.7,
        numReviews: 14,
    },
    {
        _id: '3',
        name: 'Mi Wirless Mouse',
        image: '/img/mouse.png',
        descripton: 'Mi Wirless Mouse supports Bluetooth & 2.4G wireless connectivity. Connect to two computers, and easily toggle between connections by pressing the bottom',
        brand: 'Xiaomi',
        category: 'Electronics',
        price: 899,
        countInStock: 8,
        ratings: 4.5,
        numReviews: 6,
    },
    {
        _id: '4',
        name: 'Mi 11 Ultra',
        image: '/img/phone.png',
        descripton: 'Xiaomi Mi 11 Ultra · Display (Primary) 6.81-inch (1440x3200) · Processor Qualcomm · Front Camera 20MP · Rear Camera 50MP + 48MP + 48MP · RAM 12GB · Storage 256GB.',
        brand: 'Xiaomi',
        category: 'Electronics',
        price: 69999,
        countInStock: 10,
        ratings: 5,
        numReviews: 15,
    },
    {
        _id: '5',
        name: 'Mi power bank',
        image: '/img/powerBank.png',
        descripton: 'Mi Power Bank is a portable powerhouse that offers two-way fast charging and ensures that your devices make it through the busiest and longest days.',
        brand: 'Xiaomi',
        category: 'Electronics',
        price: 1599,
        countInStock: 2,
        ratings: 4.6,
        numReviews: 12,
    },
    {
        _id: '6',
        name: 'Mi smart speaker',
        image: '/img/speaker.png',
        descripton: 'Mi Smart Speaker has a single 63.5mm full-range driver, with a rated output of 12W and sound tuning by DTS. There are two far-field ',
        brand: 'Xiaomi',
        category: 'Electronics',
        price: 3999,
        countInStock: 13,
        ratings: 3.2,
        numReviews: 7,
    },
    {
        _id: '7',
        name: 'Mi Vaccum Mop',
        image: '/img/vaccumMop.png',
        descripton: 'The new LDS Laser Navigation System works with an upgraded SLAM algorithm for real-time mapping, faster speed, higher accuracy, and longer scanning range.',
        brand: 'Xiaomi',
        category: 'Electronics',
        price: 14999,
        countInStock: 3,
        ratings: 2.4,
        numReviews: 2,
    },
    {
        _id: '8',
        name: 'Mi Smart watch',
        image: '/img/watch.png',
        descripton: 'The Mi Watch  comes with a premium Design with AMOLED Color Display 10.SPORT MODES A Battery. THAT LASTS. Made to last for up to 2 weeks straight on a single charge. and it has IP68 rating ',
        brand: 'Xiaomi',
        category: 'Electronics',
        price: 8999,
        countInStock: 11,
        ratings: 3.7,
        numReviews: 9,
    }
]

export default products